### ISSUE TITLE
Why the gulp scss throws error?

### ISSUE THREAD

**Issue by Cueroqu** [juanfran/gulp-scss-lint#35]
When I run 'gulp scss' on my mac it reports while there's no such error on another mac with same version of gulp :

    [16:40:32] Using gulpfile ~/Documents/codes/biz-tools/portal/gulpfile.js
    [16:40:32] Starting 'scss'...

    stream.js:94
        throw er; // Unhandled stream error in pipe.
            ^
    Error: Command line usage error
        at createExecError (/Users/zhun.qu/Documents/codes/biz-tools/portal/node_modules/gulp-        scsslint/src/index.js:155:33)
        at ChildProcess.<anonymous> (/Users/zhun.qu/Documents/codes/biz-tools/portal/node_modules/gulp-scsslint/src/index.js:217:26)
        at ChildProcess.emit (events.js:110:17)
        at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

But it's ok on my mac if i comment two lines in gulpfile.js

     gulp.task('scss', function() {
       return gulp.src(paths.styles)
       //    .pipe(scsslint())
       //    .pipe(scsslint.reporter())
      .pipe(sass())
      .pipe(gulp.dest('src/styles'));
    });

Does anyone know the reason?

**Comment by juanfran** [comment]
Do they have the same scss-lint gem version?

**Comment by brunowego** [comment]
+1

**Comment by brunowego** [comment]
Solved with https://github.com/brigade/scss-lint/issues/324. :+1:

**Comment by chris-dura** [comment]
I seem to be getting a similar error.
```

**Comment by chris-dura** [comment]
Also `npm install gulp-scss-lint` seems to install `0.1.12` which is behind `0.2.1` which is indicated on https://www.npmjs.com/package/gulp-scss-lint

**Comment by chris-dura** [comment]
Oop, that may have been it... I manually changed my `package.json` from `"gulp-scss-lint": "^0.1.12",` to `"gulp-scss-lint": "^0.2.1,"` and re-ran `npm install`.

Now, `gulp scss-lint-test` runs as expected.
