### ISSUE TITLE
Error: stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by michaelBenin** [juanfran/gulp-scss-lint#42]
```
Admins-MacBook-Pro:redesign-slot-fastcompany mbenin$ gulp scss-lint
[17:35:07] Requiring external module babel-core/register
[17:35:08] Using gulpfile ~/Projects/redesign-slot-fastcompany/gulpfile.babel.js
[17:35:08] Starting 'scss-lint'...
[17:35:08] Finished 'scss-lint' after 4.23 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stdout maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:678:13)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:526:21)
```

**Comment by juanfran** [comment]
Could you try to increase the maxBuffer option?

**Comment by michaelBenin** [comment]
Yup that did it! Maybe make the default greater?
