### ISSUE TITLE
ENAMETOOLONG when too many files are matched in path with wildcards

### ISSUE THREAD

**Issue by 27percent** [juanfran/gulp-scss-lint#46]
I'm hitting an issue with the number of files we're passing to gulp-scss-lint, I'm giving `gulp.src()` a path like `./themes/**/*.scss` which contains about 100 or so directories, each of which contains at least 6 scss files, so a minimum of 600 files - when I do so, gulp gives me this error:

```javascript
child_process.js:1155
    throw errnoException(err, 'spawn');
          ^
Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1155:11)
    at exports.spawn (child_process.js:988:9)
    at Object.exports.execFile (child_process.js:682:15)
    at Object.exports.exec (child_process.js:642:18)
    at execCommand (C:\Source-git\src\directory\sub_directory\node_modules\gulp-scss-lint\src\index.js:92:21)
    at execLintCommand (C:\Source-git\src\directory\sub_directory\node_modules\gulp-scss-lint\src\index.js:110:5)
    at Stream.endStream (C:\Source-git\src\directory\sub_directory\node_modules\gulp-scss-lint\src\index.js:240:5)
    at _end (C:\Source-git\src\directory\sub_directory\node_modules\gulp-scss-lint\node_modules\event-stream\node_modules\through\index.js:65:9)

    at Stream.stream.end (C:\Source-git\src\directory\sub_directory\node_modules\gulp-scss-lint\node_modules\event-stream\node_modules\through\index.js:74:5)
```

My guess is that this is due to the length of the command you're handing off to the scss-lint command line utility. Gulp is giving it a huge JSON blob of file paths for each of the individual files gulp.src matches instead of one short path with wildcards, I've tested the wildcard path approach with the scss-lint CLI tool and it works just fine so it'd be great if gulp-scss-lint supported it too, it's stopping us from using it currently.

**Comment by juanfran** [comment]
thanks for your feedback @27percent 

I have to research how to do it but meanwhile you could be set the `sync` option to `true`

**Comment by juanfran** [comment]
sorry for the long delay

now you can use gulp-scss-lint without gulp.src

https://github.com/juanfran/gulp-scss-lint#glob-pattern-without-gulpsrc
