### ISSUE TITLE
Does not properly escape file path "(" and ")" characters

### ISSUE THREAD

**Issue by gajus** [juanfran/gulp-scss-lint#47]
```
[08:14:51] Starting 'scss-lint'...
scss-lint /Users/gajus/Documents/dev/applaudience/2015\ 08\ 04\ showtimes\ (react)/src/static/main.scss /Users/gajus/Documents/dev/applaudience/2015\ 08\ 04\ showtimes\ (react)/src/static/normalise.scss --format=JSON
undefined:1


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/gajus/Documents/dev/applaudience/2015 08 04 showtimes (react)/node_modules/gulp-scss-lint/src/index.js:130:19
    at ChildProcess.exithandler (child_process.js:204:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:764:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:468:12)
```

In the above example, the following file paths are not escaped property:

* `/Users/gajus/Documents/dev/applaudience/2015\ 08\ 04\ showtimes\ (react)/src/static/main.scss`
* `/Users/gajus/Documents/dev/applaudience/2015\ 08\ 04\ showtimes\ (react)/src/static/normalise.scss`

They are missing backslashed before the "(" and ")" characters.

Therefore, these should be:

* `/Users/gajus/Documents/dev/applaudience/2015\ 08\ 04\ showtimes\ \(react\)/src/static/normalise.scss`
* `/Users/gajus/Documents/dev/applaudience/2015\ 08\ 04\ showtimes\ \(react\)/src/static/normalise.scss`

**Comment by gajus** [comment]
Please bump the package.json version.

**Comment by juanfran** [comment]
I did it yesterday

**Comment by gajus** [comment]
@juanfran I don't see it. https://github.com/juanfran/gulp-scss-lint/commit/4d43bc4f9733621119439220250f4b6980ede72c

**Comment by juanfran** [comment]
sorry @gajus I forgot to commit the package.js, now it's done, thanks

**Comment by gajus** [comment]
Thank you
