### ISSUE TITLE
Unexpected token N

### ISSUE THREAD

**Issue by Successful** [juanfran/gulp-scss-lint#57]
Getting this error when i try to lint my files:

`Unhandled rejection SyntaxError: Unexpected token N
    at Object.parse (native)
    at C:\Dev\Successful Solutions\node_modules\gulp-scss-lint\src\command.js:93:25
    at tryCatcher (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:419:13)
Unhandled rejection SyntaxError: Unexpected token N
    at Object.parse (native)
    at C:\Dev\Successful Solutions\node_modules\gulp-scss-lint\src\command.js:93:25
    at tryCatcher (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (C:\Dev\Successful Solutions\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:419:13)
Process terminated with code 0.`

With this task:

'use strict';

module.exports = function (gulp, config, plugins) {
    return {
        params: [config.isProduction],
        fn: function (isProduction, callBack) {
            gulp.src(config.paths.sources.scss)
                .pipe(plugins.cached('scssLint'))
                .pipe(plugins.scssLint(
                    {
                        'config': 'Lints/ScssLint.yml',
                        'reporterOutput': 'Lints/ScssReport.json',
                        'endless': true // True when we use gulp-watch
                    }
                ))
                .pipe(plugins.scssLint.failReporter());

            callBack();
        }
    };
};

**Comment by Successful** [comment]
After a bit of research i found out that this is a problem when i use this config file:

https://raw.githubusercontent.com/brigade/scss-lint/master/config/default.yml

**Comment by juanfran** [comment]
It works for me.

Could you add the `verbose: true` options and run the command output? Could you tell me what you get?

**Comment by Successful** [comment]
Sorry for a late answer, been testing quite much and the problem was not with this plugin.
