### ISSUE TITLE
Unhandled rejection Error: Invalid glob argument thrown when src option used

### ISSUE THREAD

**Issue by tifabien** [juanfran/gulp-scss-lint#86]
I've got an issue when using the src option instead of the default gulp.src.
When I'm running the tool on window I'm faced with the issue described in #51  
I then switched the gulp.src to the src.options but now when I run my scss lint task I got this error
`
Unhandled rejection Error: Invalid glob argument:
    at Object.src (C:\Users\me\Documents\dev\node_modules\gulp-scss-lint\node_modules\vinyl-fs\lib\src\index.js:32:11)
    at C:\Users\me\Documents\dev\node_modules\gulp-scss-lint\src\scss-lint.js:154:13
    at Promise._execute (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:79:10)
    at getVinylFiles (C:\Users\me\Documents\dev\node_modules\gulp-scss-lint\src\scss-lint.js:145:10)
    at C:\Users\me\Documents\dev\node_modules\gulp-scss-lint\src\scss-lint.js:177:11
    at tryCatcher (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:509:35)
    at Promise._settlePromise (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise_array.js:144:14)
    at PromiseArray._iterate (C:\Users\me\Documents\dev\node_modules\bluebird\js\release\promise_array.js:114:31)
`

Note that this error only occurs when all my files are OK and don't have any linting error. 
When one file is on error I have the correct output. 
From what I understand the problem could be on https://github.com/juanfran/gulp-scss-lint/blob/master/src/scss-lint.js#L171 when no error reported, we pass to the vinylFs.src method an empty array?

Maybe I missed something. Thanks for your help!

**Comment by juanfran** [comment]
thanks! fixed in the last release
